# Generated by Django 4.2.7 on 2025-10-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('ghana_card', 'Ghana Card'), ('voters_id', 'Voters Id')], default='ghana_card', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('Greater Accra-Accra', 'Greater Accra-Accra'), ('Ashanti Region', 'Ashanti Region - Kumasi'), ('Western Region', 'Western Region - Sekondi-Takoradi'), ('Eastern Region', 'Eastern Region - Koforidua'), ('Central Region', 'Central Region - Cape Coast'), ('Northern Region', 'Northern Region - Tamale'), ('Upper East Region', 'Upper East Region - Bolgatanga'), ('Upper West Region', 'Upper West Region - Wa'), ('Bono Region', 'Bono Region - Sunyani'), ('Bono East Region', 'Bono East Region - Techiman'), ('Ahafo Region', 'Ahafo Region - Goaso'), ('Western North', 'Western North Region - Sefwi Wiawso'), ('Oti Region', 'Oti Region - Dambai'), ('Volta Region', 'Volta Region - Ho'), ('North East Region', 'North East Region - Nalerigu'), ('Savannah Regio', 'Savannah Region - Damango')], default='Greater Accra-Accra', max_length=20),
        ),
    ]
