# Generated by Django 4.2.7 on 2025-10-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_id_type_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='000-0000-0000-0', max_length=30),
        ),
    ]
