# Generated by Django 4.2.7 on 2025-10-22 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NLA 5/90', 'NLA 5/90'), ('Monday Special', 'Monday Special'), ('Lucky Tuesday', 'Lucky Tuesday'), ('Midweek', 'Midweek'), ('Fortune Thursday', 'Fortune Thursday'), ('Friday Bonanza', 'Friday Bonanza'), ('National Weekly', 'National Weekly'), ('Sunday Aseda', 'Sunday Aseda'), ('VAG Games', 'VAG Games'), ('VAG Monday', 'VAG Monday'), ('VAG Tuesday', 'VAG Tuesday'), ('VAG Wednesday', 'VAG Wednesday'), ('VAG Thursday', 'VAG Thursday'), ('VAG Friday', 'VAG Friday'), ('VAG Saturdayy', 'VAG Saturdayy'), ('VAG Sunday', 'VAG Sunday'), ('Noon Rush', 'Noon Rush'), ('Noon Monday', 'Noon Monday'), ('Noon Tuesday', 'Noon Tuesday'), ('Noon Wednesday', 'Noon Wednesday'), ('Noon Thursday', 'Noon Thursday'), ('Noon Friday', 'Noon Friday'), ('Noon Saturday', 'Noon Saturday'), ('Quick 5,11', 'Quick 5/11')], max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('nla 5/90', 'NLA 5/90'), ('vag games', 'VAG Games'), ('noon rush', 'Noon Rush'), ('other games', 'Other Games')], default='nla 5/90', max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=20)),
            ],
            options={
                'db_table': 'game_types',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('game_update', 'Game Update'), ('draw_result', 'Draw Result'), ('new_game', 'New Game'), ('promotion', 'Promotion'), ('system', 'System Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('game_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.gametype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribe_at', models.DateTimeField(blank=True, null=True)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='betting.gametype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
                'unique_together': {('user', 'game_type')},
            },
        ),
    ]
