# Generated by Django 4.2.7 on 2025-10-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='bet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='betting.bettype'),
        ),
        migrations.AlterField(
            model_name='gameodds',
            name='bet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='betting.bettype'),
        ),
    ]
