# Generated by Django 4.2.7 on 2025-10-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_alter_draw_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='total_bets',
            field=models.IntegerField(default=30),
        ),
    ]
