# Generated by Django 4.2.7 on 2025-10-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_alter_draw_total_bets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='total_bets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='name',
            field=models.CharField(choices=[('Monday Special', 'Monday Special'), ('Lucky Tuesday', 'Lucky Tuesday'), ('Midweek', 'Midweek'), ('Fortune Thursday', 'Fortune Thursday'), ('Friday Bonanza', 'Friday Bonanza'), ('National Weekly', 'National Weekly'), ('Sunday Aseda', 'Sunday Aseda'), ('VAG Monday', 'VAG Monday'), ('VAG Tuesday', 'VAG Tuesday'), ('VAG Wednesday', 'VAG Wednesday'), ('VAG Thursday', 'VAG Thursday'), ('VAG Friday', 'VAG Friday'), ('VAG Saturday', 'VAG Saturday'), ('VAG Sunday', 'VAG Sunday'), ('Noon Monday', 'Noon Monday'), ('Noon Tuesday', 'Noon Tuesday'), ('Noon Wednesday', 'Noon Wednesday'), ('Noon Thursday', 'Noon Thursday'), ('Noon Friday', 'Noon Friday'), ('Noon Saturday', 'Noon Saturday'), ('Quick 5/11', 'Quick 5/11')], max_length=100),
        ),
    ]
