# Generated by Django 4.2.7 on 2025-11-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_alter_draw_total_bets_alter_gametype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettype',
            name='name',
            field=models.CharField(choices=[('direct_one', 'Direct One'), ('direct_two', 'Direct Two'), ('direct_three', 'Direct Three'), ('direct_four', 'Direct Four'), ('direct_five', 'Direct Five'), ('perm two', 'Perm Two'), ('perm three', 'Perm Three'), ('banker', 'Banker'), ('against', 'Against')], max_length=50, unique=True),
        ),
    ]
